name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag jwbaart.dev:$(date +%s)
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=false" \
            --tag jwbaart.dev:$(date +%s) \
            --file Dockerfile .
#     - name: Docker login and push
#       run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the Docker image to the registry
      run: docker push jwbaart
#       run: docker push myimage:tag

#       run: |
#         docker login --username ${{secrets.DOCKER_USERNAME}}
#         ${{secrets.DOCKER_ACCESS_TOKEN}}
#         docker push jwbaart/jwbaart.dev

#     This also builds container, should only publish
#     - name: Publish to Registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: jwbaart/jwbaart.dev
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

